include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    public_member_api_docs: true
    sort_constructors_first: true
    omit_local_variable_types: false
    use_super_parameters: true
    lines_longer_than_80_chars: false
