name: rainbow_logger
description: A colorful and expressive Flutter logger for terminal/debug output with emoji prefixes and ANSI color codes.
version: 0.0.1
homepage: https://github.com/piro-piyush/rainbow_logger

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
