name: rainbow_logger
description: A colorful and expressive Flutter logger for terminal/debug output with emoji prefixes and ANSI color codes.
version: 0.0.1
homepage: https://github.com/piro-piyush/rainbow_logger
repository: https://github.com/piro-piyush/rainbow_logger
issue_tracker: https://github.com/piro-piyush/rainbow_logger/issues
documentation: https://github.com/piro-piyush/rainbow_logger#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Optional: Include topics/tags to improve search visibility on pub.dev
topics:
  - logging
  - debug
  - terminal
  - flutter
  - ansi


# Optional but helpful for command-line Dart users
executables:
  rainbow_logger: bin/main.dart
